databases:
  - name: api_db
    plan: free
    databaseName: api_db
    user: api_db

services:
  - type: web
    name: api
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn rest_api.wsgi:application --bind 0.0.0.0:${PORT} --workers ${WEB_CONCURRENCY:-2} --preload"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rest_api.settings
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: DATABASE_URL
        fromDatabase:
          name: api_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@test.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
